### ISSUE TITLE
Released programs?

### ISSUE THREAD

**Issue by michaelsjackson** [keijiro/midi-pong#1]
Would not it be better if there would be also released programs as .exe or some other form, so we could try it immediately?
Anyway, just saw your video on vimeo, thought, how cool this is, especially when used via faders in midi controllers, rather than using knobs, as in your video. Thanks for sharing. Cool work!

**Comment by keijiro** [comment]
I developed this project seven years ago, and unfortunately, most of the things in it were deprecated.

If you're interested in how to use MIDI with Unity, please check the latest plugin: https://github.com/keijiro/Minis
